services:
    feishin:
        container_name: feishin
        image: 'ghcr.io/jeffvli/feishin:latest'
        env_file:
          - /etc/feishin.env
        environment:
            - SERVER_LOCK=true # When true AND name/type/url are set, only username/password can be toggled
            - SERVER_NAME=navidrome
            - SERVER_TYPE=navidrome
            - SERVER_URL=${SERVER_URL}
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Etc/GMT+1
        ports:
            - 9180:9180
        restart: unless-stopped
