services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /webui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://host.docker.internal:11434/api'
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
