---
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    environment:
      - BACK_URL=backend:5000 # Change this if you rename the containers
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - /etc/kitchenowl/env
      - /secrets/env
  backend:
    image: tombursch/kitchenowl-backend:latest
    restart: unless-stopped
    volumes:
      - /data:/data
    env_file:
      - /etc/kitchenowl/env
      - /secrets/env
