---
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    environment:
      - BACK_URL=backend:5000 # Change this if you rename the containers
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: tombursch/kitchenowl-backend:latest
    restart: unless-stopped
    #environment:
    #  - JWT_SECRET_KEY=PLEASE_CHANGE_ME
    volumes:
      - /data:/data
