# 2024-09-30
services:
  server:
    image: ghcr.io/arthi-chaud/meelo-server:latest
    expose:
      - 4000
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    volumes:
      - ${DATA_DIR}:${INTERNAL_DATA_DIR}
      - /music:${INTERNAL_DATA_DIR}/music:ro
      - /secrets/rendered/settings.json:${INTERNAL_CONFIG_DIR}/settings.json:ro
      - ${CONFIG_DIR}:${INTERNAL_CONFIG_DIR}
    env_file:
      - /secrets/rendered/env
    environment:
      - TRANSCODER_URL=http://transcoder:7666
      - MEILI_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:4000"]
      interval: 5s
      timeout: 5s
      retries: 5
  front:
    image: ghcr.io/arthi-chaud/meelo-front:latest
    expose:
      - 3000
    depends_on:
      server:
        condition: service_healthy
    environment:
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - SSR_SERVER_URL=http://server:4000
  redis:
    image: redis:7.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:alpine3.14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - /secrets/rendered/env
    volumes:
      - /data/db:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.5
    restart: on-failure
    expose:
      - 7700
    volumes:
      - /data/search:/meili_data
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=true
      - MEILI_MAX_INDEXING_MEMORY=8G
      - MEILI_MAX_INDEXING_THREADS=4
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://0.0.0.0:7700/health"]
      timeout: 5s
      retries: 5
  transcoder:
    image: ghcr.io/zoriya/kyoo_transcoder:master
    restart: on-failure
    cpus: 1
    expose:
      - 7666
    environment:
      - GOCODER_SAFE_PATH=${INTERNAL_DATA_DIR}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=gocoder
      - POSTGRES_SERVER=db
    volumes:
      - /music:${INTERNAL_DATA_DIR}/music:ro
      - ${DATA_DIR}:${INTERNAL_DATA_DIR}:ro
      - /data/transcoder_cache:/cache
    profiles: ['', 'cpu']
  nginx:
    restart: on-failure
    image: nginx:1.24.0-alpine
    depends_on:
      server:
        condition: service_started
      front:
        condition: service_started
    ports:
      - ${PORT:-5000}:5000
    configs:
      - source: nginx.conf.template
        target: /etc/nginx/templates/meelo.conf.template
configs:
  nginx.conf.template:
    content: |
      server {
        listen 5000 default_server;
        listen [::]:5000 default_server;
        access_log off;
        server_name _;
        
        location = /api {
          return 302 /api/;
        }
        location /api/ {
          proxy_pass http://server:4000/;
        }
        location / {
          proxy_pass http://front:3000;
        }
      }
