services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - /music:/music:ro
      - /data:/config
    ports:
      - "1970:1970"
    restart: always
