#!/usr/bin/env fish
# sysfs attributes
#----------------
#
# pwm[1-7] - this file stores PWM duty cycle or DC value (fan speed) in range:
#	     0 (lowest speed) to 255 (full)
#
# pwm[1-7]_enable - this file controls mode of fan/temperature control:
#	* 0 Fan control disabled (fans set to maximum speed)
#	* 1 Manual mode, write to pwm[0-5] any value 0-255
#	* 2 "Thermal Cruise" mode
#	* 3 "Fan Speed Cruise" mode
#	* 4 "Smart Fan III" mode (NCT6775F only)
#	* 5 "Smart Fan IV" mode

for i in 1 3 4
	set hwmon $argv[1]
	echo $argv[2] > /sys/class/hwmon/hwmon"$hwmon"/pwm$i
end
