services:
  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    environment:
      - OTR_PORT=0
      - OTR_HTTPHOST=0.0.0.0
    volumes:
      - /data/config:/config
      - /data/store:/store
    restart: always
  owntracks-frontend:
    image: owntracks/frontend
    ports:
      - 80:80
    volumes:
      - /etc/owntracks/fe-config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    restart: always
