---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=101700
      - PGID=101700
      - TZ=Europe/Prague
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /config:/config
      - /data:/data
      - /misc:/misc
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
