version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    #ports:
    #- "25565:25565"
    network_mode: host
    env_file:
      - /secrets/rendered/env
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-of-fabric-7
      CF_FILENAME_MATCHER: "1.3.2"
      MEMORY: 16G
    volumes:
      - /data:/data
      #- /downloads:/downloads
